version: 2

jobs:
  pdf_build:
    docker:
      - image: node:slim
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: npm dependencies
          command: |
            set -exu
            npm i md-to-pdf
      - run:
          name: Convert md to pdf
          command: |
            set -exu
            ls -la
            md-to-pdf ./README.md ./awesome-cka-v1.14.1.1.pdf
      - store_artifacts:
          path: ./awesome-cka-v1.14.1.1.pdf
          destination: awesome-cka-v1.14.1.1.pdf

workflows:
  version: 2
  build-release:
    jobs:
      - pdf_build